New community page
vibeverse-team/vibeverse pull request #96
Opened 2023-11-06 17:31 UTC by roger-rangel

2023-11-14 02:17 UTC, neddy34 requested changes
Overall looks good, added some changes regarding coding styles.

2023-11-14 02:17 UTC, neddy34 commented on src/app/dashboard/mycommunity/page.tsx
> +import IntroCommunity from '../../../components/community/IntroCommunity';
Please create a `index.tsx` in `src/components/community` directory and export all components in there.
And import all components like

```ts
import { IntroCommunity, ...} from '@/components/community';
...
```

2023-11-14 02:17 UTC, neddy34 commented on src/app/dashboard/mycommunity/page.tsx
> +  const [introModal, showIntroModal] = useState(true);
Please check how the other modal works like Create Collection, Mint NFT, Profile

2023-11-14 02:17 UTC, neddy34 commented on src/components/Nft/TransferModal.tsx
> +          // @ts-ignored
Please revert

2023-11-14 02:17 UTC, neddy34 commented on src/components/community/CreateCommunity.jsx
> +import ConnectSocials from '../../components/community/ConnectSocials';
Import directly in the current folder

2023-11-14 02:17 UTC, neddy34 commented on src/components/community/IntroCommunity.jsx
> +import styles from './IntroCommunity.module.scss';
Well I agree with using css modules, but I prefer using tailwindcss.

2023-11-14 02:17 UTC, neddy34 commented on src/components/community/JoinCommunity.jsx
Please change modal behavior

2023-11-14 14:02 UTC, roger-rangel commented on src/components/community/JoinCommunity.jsx
What do you mean with "modal behaviour"??

2023-11-14 14:10 UTC, neddy34 commented on src/components/community/IntroCommunity.jsx
> +import styles from './IntroCommunity.module.scss';
Yes, we can use css modules, and what I mean was if tailwind is possible please use that. :)

2023-11-16 09:19 UTC, neddy34 approved these changes

2023-11-16 09:27 UTC, merged